array : [
      ## Cross
          # 1cm
          [
            [+0.00, -0.01, +0.00],
            [-0.01, -0.00, +0.00],
            [+0.00, +0.01, +0.00],
            [+0.01, +0.00, +0.00]
          ],
          # 3cm
          [
            [+0.00, -0.03, +0.00],
            [-0.03, -0.00, +0.00],
            [+0.00, +0.03, +0.00],
            [+0.03, +0.00, +0.00]
          ],
          # 5cm
          [
            [+0.00, -0.05, +0.00],
            [-0.05, -0.00, +0.00],
            [+0.00, +0.05, +0.00],
            [+0.05, +0.00, +0.00]
          ],
          # 7cm
          [
            [+0.00, -0.07, +0.00],
            [-0.07, -0.00, +0.00],
            [+0.00, +0.07, +0.00],
            [+0.07, +0.00, +0.00]
          ]
          
        ]