array : [
      ## Cross
          # 2cm
          [
            [+0.00, -0.02, +0.00],
            [-0.02, -0.00, +0.00],
            [+0.00, +0.02, +0.00],
            [+0.02, +0.00, +0.00]
          ],
          # 4cm
          [
            [+0.00, -0.04, +0.00],
            [-0.04, -0.00, +0.00],
            [+0.00, +0.04, +0.00],
            [+0.04, +0.00, +0.00]
          ],
          # 6cm
          [
            [+0.00, -0.06, +0.00],
            [-0.06, -0.00, +0.00],
            [+0.00, +0.06, +0.00],
            [+0.06, +0.00, +0.00]
          ],
          # 8cm
          [
            [+0.00, -0.08, +0.00],
            [-0.08, -0.00, +0.00],
            [+0.00, +0.08, +0.00],
            [+0.08, +0.00, +0.00]
          ]
        ]