# Linear
          # 1cm
array : [
          [
            [+0.00, -0.015, +0.00],
            [+0.00, -0.005, +0.00],
            [+0.00, +0.005, +0.00],
            [+0.00, +0.015, +0.00]
          ],
          # 2cm
          [
            [+0.00, -0.03, +0.00],
            [+0.00, -0.01, +0.00],
            [+0.00, +0.01, +0.00],
            [+0.00, +0.03, +0.00]
          ],
          # 3cm
          [
            [+0.00, -0.045, +0.00],
            [+0.00, -0.015, +0.00],
            [+0.00, +0.015, +0.00],
            [+0.00, +0.045, +0.00]
          ],
          # 4cm
          [
            [+0.00, -0.06, +0.00],
            [+0.00, -0.02, +0.00],
            [+0.00, +0.02, +0.00],
            [+0.00, +0.06, +0.00]
          ],
          # 5cm
          [
            [+0.00, -0.075, +0.00],
            [+0.00, -0.025, +0.00],
            [+0.00, +0.025, +0.00],
            [+0.00, +0.075, +0.00]
          ],
          # 6cm
          [
            [+0.00, -0.09, +0.00],
            [+0.00, -0.03, +0.00],
            [+0.00, +0.03, +0.00],
            [+0.00, +0.09, +0.00]
          ],
          # 7cm
          [
            [+0.00, -0.105, +0.00],
            [+0.00, -0.035, +0.00],
            [+0.00, +0.035, +0.00],
            [+0.00, +0.105, +0.00]
          ],
          # 8cm
          [
            [+0.00, -0.12, +0.00],
            [+0.00, -0.04, +0.00],
            [+0.00, +0.04, +0.00],
            [+0.00, +0.12, +0.00]
         ]
        ]