# Linear
          # 1cm
array : [
          [
            [+0.00, -0.015, +0.00],
            [+0.00, -0.005, +0.00],
            [+0.00, +0.005, +0.00],
            [+0.00, +0.015, +0.00]
          ],
          # 3cm
          [
            [+0.00, -0.045, +0.00],
            [+0.00, -0.015, +0.00],
            [+0.00, +0.015, +0.00],
            [+0.00, +0.045, +0.00]
          ],
          # 5cm
          [
            [+0.00, -0.075, +0.00],
            [+0.00, -0.025, +0.00],
            [+0.00, +0.025, +0.00],
            [+0.00, +0.075, +0.00]
          ],
          # 7cm
          [
            [+0.00, -0.105, +0.00],
            [+0.00, -0.035, +0.00],
            [+0.00, +0.035, +0.00],
            [+0.00, +0.105, +0.00]
          ]
        ]