version : 3

# Params
n_base : 100
sec : 5
max_src : 3

# audio
n_mic : 4
mic_min_dist : 0.02
mic_max_dist : 0.06
sr : 16000

# data
use_noise : False
multiple_train : 100

ratio_train : 0.9
ratio_dev : 0.05
ratio_eval : 0.05

# PATH
output_root : "/home/data2/kbh/DOA"
CHiME4_root : "/home/data/kbh/CHiME4/isolated_ext"